apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ca-sink-creator
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: message-sink-app
  targetCPUUtilizationPercentage: 30